### ISSUE TITLE
Frequent input drops and not so frequent misinputs

### ISSUE THREAD

**Issue by HiLordReilo** [BlueGlassBlock/toucca#5]
Not sure how to form this issue, neither can say what might be causing it. Inputs seem to drop frequently on fast patterns and, sometimes, inputs are registering on top part or in the opposite side of the ring (this one could be a problem with relative mode). Tried API Version 1 and 256 on Release branch, but both seem to have this issue. Tested on Reverse 3.07.01

**Comment by HiLordReilo** [comment]
I should've done more testing on my touchscreen, turns out the device itself is dropping inputs. My apologies....

**Comment by BlueGlassBlock** [comment]
> inputs are registering on top part or in the opposite side of the ring (this one could be a problem with relative mode)

Can you confirm whether this issue persists? Relative mode and absolute mode share **the same** code when parsing touch points into rotation regions (1 - 60) with different logic in handling ring index (0 - 3).
