### ISSUE TITLE
文件报错找不到FILE COM5

### ISSUE THREAD

**Issue by 45231hgjkl** [BlueGlassBlock/toucca#8]
控制台报错
--- Begin mercury_pre_startup ---
DVD: hook enabled.
Reg hook init
Wacca IO: Using custom IO DLL: toucca.dll
 INFO new: toucca_lib::serial: Trying to start serial ports
Toucca panicked: panicked at toucca-lib\src\serial\mod.rs:33:14:
Failed to open COM5: Error { kind: NoDevice, description: "系统找不到指定的文件。" }Game processes have terminated
在Seriamanager.cs中30行出现中断
但是COM6未发生报错

**Comment by BlueGlassBlock** [comment]
旧版和新版不能共存的，也就是不应该同时使用 toucca.dll 与 toucca C# (exe)

**Comment by 45231hgjkl** [comment]
在C#上只是debug哪个部分出问题，在实际使用的时候只调用了dll
在使用Any1WACCAi的时候也会找不到file COM5
感觉可能是同样的问题

**Comment by BlueGlassBlock** [comment]
C# 和 DLL 本身实现不一样的

找不到文件可以检查下 com0com 有没有正确配置，xiaopeng12318/WACVR 那里的安装包应该是有端口预设的

**Comment by BlueGlassBlock** [comment]
如果无法解决请再联系
